# Generated by Django 5.0.3 on 2024-03-29 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instituto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='Comisión',
            new_name='Comision',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='Comisión',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='Comisión',
        ),
    ]
